name: transethnic_prs
channels:
  - conda-forge
  - main
  - defaults
dependencies:
  - ipython
  - jax=0.2.10
  - jupyter
  - matplotlib=3.3.4
  - numpy=1.19
  - pandas=1.2
  - pandas-plink=2.2.4
  - pip=21.0.1
  - python=3.7
  - scikit-learn=0.24.1
  - scipy=1.6.1
  - seaborn=0.11
  - numba=0.53
  # - pip:
  #   - rpy2==3.4.2
# prefix: path-to-conda-directory/envs/transethnic_prs
